#!/usr/bin/env python

MQTT_CLIENT_STATUS_TOPIC = '/mqtt2cmd/status'
MQTT_CLIENT_PING_TOPIC = '/mqtt2cmd/ping'
MQTT_CLIENT_PING_INTERVAL_SECS = 666
CONFIG_DEFAULT_PAYLOAD = 'default'
CONFIG_ATTRS = 'attrs'
CONFIG_VARS = 'vars'
CONFIG_CMDS = 'cmds'
CONFIG_VARIABLE_PREFIX = '@'
CONFIG_VARIABLE_SUFFIX = ''
CONFIG_TIMEOUT = 'timeout'
CONFIG_TIMEOUT_DEFAULT_SECS = 25
CONFIG_STOP = 'stop_on_failure'
CONFIG_STOP_DEFAULT = True
CONFIG_IN_SEQ = 'in_sequence'
CONFIG_IN_SEQ_DEFAULT = True
