#!/usr/bin/env python

MQTT_CLIENT_ID_DEFAULT = 'mqtt2cmd'
MQTT_CLIENT_DEFAULT_TOPIC_STATUS = '/mqtt2cmd/status'
MQTT_CLIENT_DEFAULT_TOPIC_PING = '/mqtt2cmd/ping'
MQTT_CLIENT_PING_INTERVAL_SECS = 666
MQTT_DEFAULT_BROKER_IP = "192.168.10.238"
CONFIG_DEFAULT_PAYLOAD = 'default'
CONFIG_ATTRS = 'attrs'
CONFIG_VARS = 'vars'
CONFIG_CMD = 'cmd'
CONFIG_CMDS = 'cmds'
CONFIG_VARIABLE_PREFIX = '%'
CONFIG_VARIABLE_SUFFIX = ''
CONFIG_TIMEOUT = 'timeout'
CONFIG_TIMEOUT_DEFAULT_SECS = 25
CONFIG_STOP = 'stop_on_failure'
CONFIG_STOP_DEFAULT = True
CONFIG_IN_SEQ = 'in_sequence'
CONFIG_IN_SEQ_DEFAULT = True
CONFIG_LOG_CMD_OUTPUT = 'log_output'
CONFIG_LOG_CMD_OUTPUT_DEFAULT = False
CONFIG_SHELL = 'shell'
CONFIG_SHELL_DEFAULT = False
